<?php
namespace Affinity;
final class OrdersBatchesResource{
public function __construct(private SdkContext $context){}
/** @param array{userId?: string|null, prescriber?: array{id?: string|null, npi?: string|null, externalId?: string|null, profile?: array{email?: string|null, phone?: string|null}|null}|null, orders: list<array{otcItems?: list<array{catalogItemId: string, quantity: int}>|null, externalOrderId?: string|null, metadata?: mixed|null, patientId?: string|null, patient?: array{address?: array{city: string, line1: string, line2?: string|null|null, postalCode: string, state: string, country?: string|null}|null|null, clinicalProfile?: array{currentMedications: list<string>, heightInches?: float|string|null|null, reviewedAt?: string|null|null, weightPounds?: float|string|null|null}|null, dateOfBirth: string, email?: string|null|null, externalId?: string|null, externalIdentities?: list<array{source: string, value: string}>|null, addresses?: list<array{id?: string|null, address: array{city: string, country?: string|null, line1: string, line2?: string|null|null, postalCode: string, state: string}, label: string, preferredShipping: bool, recipientName: string|null}>|null, encounters?: list<array{notes: string|null, occurredAt: string, providerName: string|null, type: string}>|null, gender?: string|null, locationId?: string|null, metadata?: mixed|null, medicalRecordNumber?: string|null|null, measurements?: list<array{heightCentimeters: float|string|null, recordedAt: string, source: string, weightKilograms: float|string|null}>|null, name: array{first: string, last: string, middle?: string|null|null, preferred?: string|null|null}, phone?: string|null|null, programs?: list<array{endedAt: string|null, name: string, startedAt: string, status: string}>|null}|null, shippingAddressId?: string|null, prescriptions: list<array{externalPrescriptionId?: string|null, clinical?: array{compoundingReason?: array{category?: string|null, context?: string|null}|null, medicationReviewStatus?: string|null, diagnosisReviewStatus?: string|null, currentMedications?: list<string>|null, diagnoses?: list<array{code: string, display: string}>|null, observations?: list<array{display: string, unit: string, value: float|string}>|null}|null, pharmacyId?: string|null, daysSupply: int, dispensing: array{dispenseUponAcceptance?: bool|null, shippingOptionId?: string|null, shippingAmountCents?: int|null, shippingDestinationType?: string|null, pharmacyNotes?: string|null, requestedFillDate?: string|null, substitutionPermitted?: bool|null}, directions: string, medicationId: string, quantity: float|string, quantityUnit: string, refills: int, structuredSig?: array{dose: string, doseUnit: string, duration?: string|null, frequency: string, indication?: string|null, maxDailyUse?: string|null, prn?: bool|null, route: string, titrationSchedule?: string|null}|null}>}>} $params
 * @param array{practiceId?: string, idempotencyKey?: string, organizationId?: string, actorId?: string, actorType?: string} $options
 */
public function create(array $params, array $options = []): \Affinity\Types\CreateOrderBatchResponse{
$result=$this->context->call('createOrderBatch',[],$params,$options);
return \Affinity\Types\CreateOrderBatchResponse::fromJson(json_encode($result, JSON_THROW_ON_ERROR));}
}
